version: '3.8'

services:
  pdfapp:
    build: 
      context: .
    # este servicio se puede usar sin nginx pero debes habilitar los puertos
    # ports:
    #   - "94:94"
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 92
    expose:
      - 92
    volumes:
      - ./app:/app/
    # environment:
    #   - SERVER_HOST=mysqldb_mariadb_1

  nginx:
    image: nginx:latest
    ports:
      - "9292:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=pdf.luque.site
      - LETSENCRYPT_HOST=pdf.luque.site
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pdfapp

networks:
  default:
    name: web_private_red_webapps #docker-redis_default #dbs_red_db
    external: true
